#!/bin/bash
#SBATCH -J cl                           
#SBATCH -o cl-%j.out                       
#SBATCH -p compute 
#SBATCH -N 1                           
#SBATCH -t 20:00:00   
#SBATCH --mem 128G 
#SBATCH --gres=gpu:a100-sxm4-80gb:1  

export CUDA_DEVICE_ORDER="PCI_BUS_ID"

port=$(shuf -i25000-30000 -n1)  

CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task748_glucose_reverse_cause_event_detection \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --load_best_model_at_end \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task073_commonsenseqa_answer_generation \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task073_commonsenseqa_answer_generation \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1590_diplomacy_text_generation \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1590_diplomacy_text_generation \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task639_multi_woz_user_utterance_generation \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task639_multi_woz_user_utterance_generation \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1572_samsum_summary \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1572_samsum_summary \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1687_sentiment140_classification \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification \
   --per_device_train_batch_size 32 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 1 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1687_sentiment140_classification \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task591_sciq_answer_generation \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation \
   --per_device_train_batch_size 32 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 1 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task591_sciq_answer_generation \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task363_sst2_polarity_classification \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification \
   --per_device_train_batch_size 32 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 1 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task363_sst2_polarity_classification \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1510_evalution_relation_extraction \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction \
   --per_device_train_batch_size 32 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 1 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1510_evalution_relation_extraction \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1729_personachat_generate_next \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1729_personachat_generate_next \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task181_outcome_extraction \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task181_outcome_extraction \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task511_reddit_tifu_long_text_summarization \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization \
   --per_device_train_batch_size 16 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 2 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task511_reddit_tifu_long_text_summarization \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task002_quoref_answer_generation \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/13-task002_quoref_answer_generation \
   --per_device_train_batch_size 16 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 2 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task002_quoref_answer_generation \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/13-task002_quoref_answer_generation/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/13-task002_quoref_answer_generation/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/13-task002_quoref_answer_generation/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task1290_xsum_summarization \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/14-task1290_xsum_summarization \
   --per_device_train_batch_size 8 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 4 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task1290_xsum_summarization \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1


CUDA_VISIBLE_DEVICES=$1 python src/run_t5.py \
   --do_train \
   --do_predict \
   --predict_with_generate \
   --model_name_or_path $2 \
   --load_checkpoint_from logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/14-task1290_xsum_summarization/saved_weights/trans_input.pt \
   --previous_lora_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/1-task748_glucose_reverse_cause_event_detection/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/2-task073_commonsenseqa_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/3-task1590_diplomacy_text_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/4-task639_multi_woz_user_utterance_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/5-task1572_samsum_summary/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/6-task1687_sentiment140_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/7-task591_sciq_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/8-task363_sst2_polarity_classification/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/9-task1510_evalution_relation_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/10-task1729_personachat_generate_next/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/11-task181_outcome_extraction/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/12-task511_reddit_tifu_long_text_summarization/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/13-task002_quoref_answer_generation/saved_weights,logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/14-task1290_xsum_summarization/saved_weights \
   --previous_prompt_key_path logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/14-task1290_xsum_summarization/saved_weights/prompts_keys_till_now.pt \
   --data_dir CL_Benchmark \
   --task_order task748_glucose_reverse_cause_event_detection,task073_commonsenseqa_answer_generation,task1590_diplomacy_text_generation,task639_multi_woz_user_utterance_generation,task1572_samsum_summary,task1687_sentiment140_classification,task591_sciq_answer_generation,task363_sst2_polarity_classification,task1510_evalution_relation_extraction,task1729_personachat_generate_next,task181_outcome_extraction,task511_reddit_tifu_long_text_summarization,task002_quoref_answer_generation,task1290_xsum_summarization,task875_emotion_classification \
   --gen_data_dir generated_data/lora_gen_superni_t5 \
   --task_config_dir configs/gen_script_superni_order2_t5_configs/task875_emotion_classification \
   --output_dir logs_and_outputs/gen_script_superni_order2_t5_inflora/outputs/15-task875_emotion_classification \
   --per_device_train_batch_size 32 \
   --per_device_eval_batch_size 128 \
   --gradient_accumulation_steps 1 \
   --learning_rate 0.0003 \
   --num_train_epochs 100 \
   --run_name gen_script_superni_order2_t5_inflora \
   --max_source_length 512 \
   --max_target_length 50 \
   --generation_max_length 50 \
   --add_task_name False \
   --add_dataset_name False \
   --overwrite_output_dir \
   --overwrite_cache \
   --lr_scheduler_type constant \
   --warmup_steps 0 \
   --logging_strategy steps \
   --logging_steps 10 \
   --metric_for_best_model eval_rougeL_for_task875_emotion_classification \
   --evaluation_strategy steps \
   --save_strategy steps \
   --save_total_limit 1 \
   --load_best_model_at_end \
   --lora_r 4 \
   --lora_alpha 32 \
   --lora_dropout 0.0 \
   --add_instruction_replay \
   --data_replay_freq -1 \
   --replay_after_n_epoch 0 \
   --model_name inflora \
   --threshold 0.995 \
   --kl_ratio 0.5 \
   --attn_temperature 1

python score.py gen_script_superni_order2_t5_inflora gen_script_superni_order2_t5_inflora
